package org.zhiwei.compose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006C53)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7FF8D0)
val md_theme_light_onPrimaryContainer = Color(0xFF002117)
val md_theme_light_secondary = Color(0xFF406917)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC0F190)
val md_theme_light_onSecondaryContainer = Color(0xFF0E2000)
val md_theme_light_tertiary = Color(0xFF006B5A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF79F8DB)
val md_theme_light_onTertiaryContainer = Color(0xFF00201A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FFF3)
val md_theme_light_onBackground = Color(0xFF00210E)
val md_theme_light_surface = Color(0xFFF5FFF3)
val md_theme_light_onSurface = Color(0xFF00210E)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DF)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4944)
val md_theme_light_outline = Color(0xFF707974)
val md_theme_light_inverseOnSurface = Color(0xFFC2FFD0)
val md_theme_light_inverseSurface = Color(0xFF00391C)
val md_theme_light_inversePrimary = Color(0xFF61DBB5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006C53)
val md_theme_light_outlineVariant = Color(0xFFBFC9C3)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF61DBB5)
val md_theme_dark_onPrimary = Color(0xFF00382A)
val md_theme_dark_primaryContainer = Color(0xFF00513E)
val md_theme_dark_onPrimaryContainer = Color(0xFF7FF8D0)
val md_theme_dark_secondary = Color(0xFFA5D576)
val md_theme_dark_onSecondary = Color(0xFF1B3700)
val md_theme_dark_secondaryContainer = Color(0xFF2A5000)
val md_theme_dark_onSecondaryContainer = Color(0xFFC0F190)
val md_theme_dark_tertiary = Color(0xFF5ADBC0)
val md_theme_dark_onTertiary = Color(0xFF00382E)
val md_theme_dark_tertiaryContainer = Color(0xFF005143)
val md_theme_dark_onTertiaryContainer = Color(0xFF79F8DB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00210E)
val md_theme_dark_onBackground = Color(0xFF99F7B5)
val md_theme_dark_surface = Color(0xFF00210E)
val md_theme_dark_onSurface = Color(0xFF99F7B5)
val md_theme_dark_surfaceVariant = Color(0xFF3F4944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C3)
val md_theme_dark_outline = Color(0xFF89938E)
val md_theme_dark_inverseOnSurface = Color(0xFF00210E)
val md_theme_dark_inverseSurface = Color(0xFF99F7B5)
val md_theme_dark_inversePrimary = Color(0xFF006C53)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF61DBB5)
val md_theme_dark_outlineVariant = Color(0xFF3F4944)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1BA784)
