package org.zhiwei.compose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF87458A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6FA)
val md_theme_light_onPrimaryContainer = Color(0xFF36003C)
val md_theme_light_secondary = Color(0xFF006C4D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF88F8C8)
val md_theme_light_onSecondaryContainer = Color(0xFF002115)
val md_theme_light_tertiary = Color(0xFF745B00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE08A)
val md_theme_light_onTertiaryContainer = Color(0xFF241A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FEFF)
val md_theme_light_onBackground = Color(0xFF002022)
val md_theme_light_surface = Color(0xFFF3FEFF)
val md_theme_light_onSurface = Color(0xFF002022)
val md_theme_light_surfaceVariant = Color(0xFFEDDEE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFFFAACF9)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF87458A)
val md_theme_light_outlineVariant = Color(0xFFD0C3CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFAACF9)
val md_theme_dark_onPrimary = Color(0xFF521458)
val md_theme_dark_primaryContainer = Color(0xFF6C2D70)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FA)
val md_theme_dark_secondary = Color(0xFF6BDBAD)
val md_theme_dark_onSecondary = Color(0xFF003826)
val md_theme_dark_secondaryContainer = Color(0xFF005139)
val md_theme_dark_onSecondaryContainer = Color(0xFF88F8C8)
val md_theme_dark_tertiary = Color(0xFFF1C100)
val md_theme_dark_onTertiary = Color(0xFF3D2F00)
val md_theme_dark_tertiaryContainer = Color(0xFF574400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE08A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002022)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF002022)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFF87458A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFAACF9)
val md_theme_dark_outlineVariant = Color(0xFF4D444C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFC8ADC4)
